apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: app-code
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-conf

      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d

        - name: php-fpm
          image: php:8.3-fpm
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
